INFO 2024-12-26 20:55:39,357 autoreload 26040 15168 Watching for file changes with StatReloader
INFO 2024-12-26 20:56:20,940 autoreload 26040 15168 C:\Users\SlimShady\Desktop\Auto\backendtesting\tradingview_alerts\tradingview_alerts\settings.py changed, reloading.
INFO 2024-12-26 20:56:21,680 autoreload 19288 23160 Watching for file changes with StatReloader
INFO 2024-12-26 20:56:35,094 autoreload 27584 22988 Watching for file changes with StatReloader
ERROR 2024-12-26 20:56:41,155 exception 27584 24376 Invalid HTTP_HOST header: '139.59.121.41'. You may need to add '139.59.121.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '139.59.121.41'. You may need to add '139.59.121.41' to ALLOWED_HOSTS.
WARNING 2024-12-26 20:56:41,157 log 27584 24376 Bad Request: /alerts/latest
WARNING 2024-12-26 20:56:41,159 basehttp 27584 24376 "GET /alerts/latest HTTP/1.1" 400 143
ERROR 2024-12-26 21:00:49,218 exception 27584 26276 Invalid HTTP_HOST header: '139.59.121.41'. You may need to add '139.59.121.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '139.59.121.41'. You may need to add '139.59.121.41' to ALLOWED_HOSTS.
WARNING 2024-12-26 21:00:49,218 log 27584 26276 Bad Request: /alerts/latest
WARNING 2024-12-26 21:00:49,218 basehttp 27584 26276 "GET /alerts/latest HTTP/1.1" 400 143
INFO 2024-12-26 21:00:58,415 autoreload 21880 11352 Watching for file changes with StatReloader
ERROR 2024-12-26 21:01:03,826 exception 21880 23968 Invalid HTTP_HOST header: '127.0.0.1'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2024-12-26 21:01:03,830 log 21880 23968 Bad Request: /
WARNING 2024-12-26 21:01:03,830 basehttp 21880 23968 "GET / HTTP/1.1" 400 143
ERROR 2024-12-26 21:01:03,913 exception 21880 24180 Invalid HTTP_HOST header: '127.0.0.1'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2024-12-26 21:01:03,914 log 21880 24180 Bad Request: /favicon.ico
WARNING 2024-12-26 21:01:03,914 basehttp 21880 24180 "GET /favicon.ico HTTP/1.1" 400 143
INFO 2024-12-26 21:01:57,153 autoreload 24000 2560 Watching for file changes with StatReloader
ERROR 2024-12-26 21:02:13,511 exception 24000 23324 Invalid HTTP_HOST header: '139.59.121.41'. You may need to add '139.59.121.41' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\middleware\security.py", line 28, in process_request
    host = self.redirect_host or request.get_host()
  File "C:\Users\SlimShady\miniconda3\envs\autobot\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '139.59.121.41'. You may need to add '139.59.121.41' to ALLOWED_HOSTS.
WARNING 2024-12-26 21:02:13,514 log 24000 23324 Bad Request: /alerts/latest
WARNING 2024-12-26 21:02:13,514 basehttp 24000 23324 "GET /alerts/latest HTTP/1.1" 400 143
INFO 2024-12-26 21:03:00,503 autoreload 25892 24448 Watching for file changes with StatReloader
INFO 2024-12-26 21:03:12,585 basehttp 25892 3636 "GET /alerts/latest HTTP/1.1" 301 0
INFO 2024-12-26 21:03:33,241 basehttp 25892 26648 "GET /alerts/latest HTTP/1.1" 301 0
INFO 2024-12-26 21:03:41,154 basehttp 25892 17820 "GET /alerts/latest HTTP/1.1" 301 0
